<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sonata\AdminBundle\Command\ListAdminCommand' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Command/ListAdminCommand.php';

$this->services['Sonata\\AdminBundle\\Command\\ListAdminCommand'] = $instance = new \Sonata\AdminBundle\Command\ListAdminCommand(${($_ = isset($this->services['sonata.admin.pool']) ? $this->services['sonata.admin.pool'] : $this->getSonata_Admin_PoolService()) && false ?: '_'});

$instance->setName('sonata:admin:list');

return $instance;
