<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.classification.manager.collection' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/classification-bundle/src/Model/CollectionManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/classification-bundle/src/Entity/CollectionManager.php';

return $this->services['sonata.classification.manager.collection'] = new \Sonata\ClassificationBundle\Entity\CollectionManager('Application\\Sonata\\ClassificationBundle\\Entity\\Collection', ${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
