<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.news.serializer.handler.post' shared service.

include_once $this->targetDirs[3].'/vendor/jms/serializer/src/Handler/SubscribingHandlerInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/core-bundle/src/Serializer/SerializerHandlerInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/core-bundle/src/Serializer/BaseSerializerHandler.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/news-bundle/src/Serializer/PostSerializerHandler.php';

return $this->services['sonata.news.serializer.handler.post'] = new \Sonata\NewsBundle\Serializer\PostSerializerHandler(${($_ = isset($this->services['sonata.news.manager.post']) ? $this->services['sonata.news.manager.post'] : $this->load('getSonata_News_Manager_PostService.php')) && false ?: '_'});
