<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.classification.serializer.handler.collection' shared service.

include_once $this->targetDirs[3].'/vendor/jms/serializer/src/Handler/SubscribingHandlerInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/core-bundle/src/Serializer/SerializerHandlerInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/core-bundle/src/Serializer/BaseSerializerHandler.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/classification-bundle/src/Serializer/CollectionSerializerHandler.php';

return $this->services['sonata.classification.serializer.handler.collection'] = new \Sonata\ClassificationBundle\Serializer\CollectionSerializerHandler(${($_ = isset($this->services['sonata.classification.manager.collection']) ? $this->services['sonata.classification.manager.collection'] : $this->load('getSonata_Classification_Manager_CollectionService.php')) && false ?: '_'});
