<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.templating.name_parser' shared service.

@trigger_error('The "sonata.templating.name_parser" service is deprecated since sonata-project/block-bundle 3.17 and will be removed in version 4.0.', E_USER_DEPRECATED);

return $this->services['sonata.templating.name_parser'] = new \Sonata\BlockBundle\Templating\TemplateNameParser(${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel', 1)) && false ?: '_'});
