<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.news.status.comment' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/core-bundle/src/Twig/Status/StatusClassRendererInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/news-bundle/src/Status/CommentStatusRenderer.php';

return $this->services['sonata.news.status.comment'] = new \Sonata\NewsBundle\Status\CommentStatusRenderer();
