<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.news.manager.comment' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/news-bundle/src/Model/CommentManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/news-bundle/src/Entity/CommentManager.php';

return $this->services['sonata.news.manager.comment'] = new \Sonata\NewsBundle\Entity\CommentManager('Application\\Sonata\\NewsBundle\\Entity\\Comment', ${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, ${($_ = isset($this->services['sonata.news.manager.post']) ? $this->services['sonata.news.manager.post'] : $this->load('getSonata_News_Manager_PostService.php')) && false ?: '_'});
