<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.news.mailer' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/news-bundle/src/Mailer/MailerInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/news-bundle/src/Mailer/Mailer.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/news-bundle/src/Util/HashGeneratorInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/news-bundle/src/Util/HashGenerator.php';

return $this->services['sonata.news.mailer'] = new \Sonata\NewsBundle\Mailer\Mailer(${($_ = isset($this->services['swiftmailer.mailer.default']) ? $this->services['swiftmailer.mailer.default'] : $this->load('getSwiftmailer_Mailer_DefaultService.php')) && false ?: '_'}, ${($_ = isset($this->services['sonata.news.blog']) ? $this->services['sonata.news.blog'] : $this->getSonata_News_BlogService()) && false ?: '_'}, ${($_ = isset($this->services['sonata.news.hash.generator']) ? $this->services['sonata.news.hash.generator'] : ($this->services['sonata.news.hash.generator'] = new \Sonata\NewsBundle\Util\HashGenerator('secureToken'))) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'}, ${($_ = isset($this->services['sonata.templating']) ? $this->services['sonata.templating'] : $this->load('getSonata_TemplatingService.php')) && false ?: '_'}, ['notification' => ['emails' => [0 => 'email@example.org', 1 => 'email2@example.org'], 'from' => 'no-reply@sonata-project.org', 'template' => '@SonataNews/Mail/comment_notification.txt.twig']]);
