<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.classification.manager.context' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/classification-bundle/src/Model/ContextManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/classification-bundle/src/Entity/ContextManager.php';

return $this->services['sonata.classification.manager.context'] = new \Sonata\ClassificationBundle\Entity\ContextManager('Application\\Sonata\\ClassificationBundle\\Entity\\Context', ${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
