<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.classification.form.type.category_selector' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractType.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/classification-bundle/src/Form/Type/CategorySelectorType.php';

return $this->services['sonata.classification.form.type.category_selector'] = new \Sonata\ClassificationBundle\Form\Type\CategorySelectorType(${($_ = isset($this->services['sonata.classification.manager.category']) ? $this->services['sonata.classification.manager.category'] : $this->load('getSonata_Classification_Manager_CategoryService.php')) && false ?: '_'});
