<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sonata\NewsBundle\Action\ModerateCommentAction' shared service.

include_once $this->targetDirs[3].'\\vendor\\sonata-project\\news-bundle\\src\\Action\\ModerateCommentAction.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\news-bundle\\src\\Util\\HashGeneratorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\news-bundle\\src\\Util\\HashGenerator.php';

return $this->services['Sonata\NewsBundle\Action\ModerateCommentAction'] = new \Sonata\NewsBundle\Action\ModerateCommentAction(${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'}, ${($_ = isset($this->services['sonata.news.blog']) ? $this->services['sonata.news.blog'] : $this->getSonata_News_BlogService()) && false ?: '_'}, ${($_ = isset($this->services['sonata.news.manager.comment']) ? $this->services['sonata.news.manager.comment'] : $this->load('getSonata_News_Manager_CommentService.php')) && false ?: '_'}, ${($_ = isset($this->services['sonata.news.hash.generator']) ? $this->services['sonata.news.hash.generator'] : ($this->services['sonata.news.hash.generator'] = new \Sonata\NewsBundle\Util\HashGenerator('secureToken'))) && false ?: '_'});
