<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata_translation.locale_switcher.user_locale_subscriber' shared service.

include_once $this->targetDirs[3].'\\vendor\\sonata-project\\translation-bundle\\src\\EventSubscriber\\UserLocaleSubscriber.php';

return $this->services['sonata_translation.locale_switcher.user_locale_subscriber'] = new \Sonata\TranslationBundle\EventSubscriber\UserLocaleSubscriber(${($_ = isset($this->services['session']) ? $this->services['session'] : $this->load('getSessionService.php')) && false ?: '_'});
