<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.news.block.breadcrumb_post' shared service.

return $this->services['sonata.news.block.breadcrumb_post'] = new \Sonata\NewsBundle\Block\Breadcrumb\NewsPostBreadcrumbBlockService('news_post', 'sonata.news.block.breadcrumb_post', ${($_ = isset($this->services['sonata.templating']) ? $this->services['sonata.templating'] : $this->load('getSonata_TemplatingService.php')) && false ?: '_'}, ${($_ = isset($this->services['knp_menu.menu_provider']) ? $this->services['knp_menu.menu_provider'] : $this->getKnpMenu_MenuProviderService()) && false ?: '_'}, ${($_ = isset($this->services['knp_menu.factory']) ? $this->services['knp_menu.factory'] : $this->load('getKnpMenu_FactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['sonata.news.blog']) ? $this->services['sonata.news.blog'] : $this->getSonata_News_BlogService()) && false ?: '_'});
