<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.news.form.comment.status_type' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Form\\FormTypeInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Form\\AbstractType.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\core-bundle\\src\\Form\\Type\\BaseStatusType.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\news-bundle\\src\\Form\\Type\\CommentStatusType.php';

return $this->services['sonata.news.form.comment.status_type'] = new \Sonata\NewsBundle\Form\Type\CommentStatusType('Application\\Sonata\\NewsBundle\\Entity\\Comment', 'getStatusList', 'sonata_news_comment_status');
