<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.formatter.validator.formatter' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Validator\\ConstraintValidatorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Validator\\ConstraintValidator.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\formatter-bundle\\src\\Validator\\Constraints\\FormatterValidator.php';

return $this->services['sonata.formatter.validator.formatter'] = new \Sonata\FormatterBundle\Validator\Constraints\FormatterValidator(${($_ = isset($this->services['sonata.formatter.pool']) ? $this->services['sonata.formatter.pool'] : $this->getSonata_Formatter_PoolService()) && false ?: '_'});
