<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUh7bxgp\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUh7bxgp/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUh7bxgp.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUh7bxgp\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUh7bxgp\appProdProjectContainer([
    'container.build_hash' => 'Uh7bxgp',
    'container.build_id' => '96f8cc42',
    'container.build_time' => 1555682312,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUh7bxgp');
