<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sonata\UserBundle\Action\LogoutAction' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/user-bundle/src/Action/LogoutAction.php';

return $this->services['Sonata\\UserBundle\\Action\\LogoutAction'] = new \Sonata\UserBundle\Action\LogoutAction();
