<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.user.mailer.default' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/user-bundle/Mailer/MailerInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/user-bundle/src/Mailer/Mailer.php';

return $this->services['sonata.user.mailer.default'] = new \Sonata\UserBundle\Mailer\Mailer(${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'}, ${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->getTwigService()) && false ?: '_'}, ${($_ = isset($this->services['swiftmailer.mailer.default']) ? $this->services['swiftmailer.mailer.default'] : $this->load('getSwiftmailer_Mailer_DefaultService.php')) && false ?: '_'}, $this->parameters['fos_user.resetting.email.from_email'], '@FOSUser/Resetting/email.txt.twig');
