<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata_translation.checker.translatable' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/translation-bundle/src/Checker/TranslatableChecker.php';

$this->services['sonata_translation.checker.translatable'] = $instance = new \Sonata\TranslationBundle\Checker\TranslatableChecker();

$instance->setSupportedInterfaces([]);
$instance->setSupportedModels([]);

return $instance;
