<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.news.permalink.collection' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/news-bundle/src/Permalink/CollectionPermalink.php';

return $this->services['sonata.news.permalink.collection'] = new \Sonata\NewsBundle\Permalink\CollectionPermalink();
