<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.classification.manager.category' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/classification-bundle/src/Model/CategoryManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/classification-bundle/src/Entity/CategoryManager.php';

return $this->services['sonata.classification.manager.category'] = new \Sonata\ClassificationBundle\Entity\CategoryManager('Application\\Sonata\\ClassificationBundle\\Entity\\Category', ${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, ${($_ = isset($this->services['sonata.classification.manager.context']) ? $this->services['sonata.classification.manager.context'] : $this->load('getSonata_Classification_Manager_ContextService.php')) && false ?: '_'});
