<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.templating' shared service.

@trigger_error('The "sonata.templating" service is deprecated since sonata-project/block-bundle 3.17 and will be removed in version 4.0.', E_USER_DEPRECATED);

return $this->services['sonata.templating'] = new \Sonata\BlockBundle\Templating\TwigEngine(${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->getTwigService()) && false ?: '_'}, ${($_ = isset($this->services['sonata.templating.name_parser']) ? $this->services['sonata.templating.name_parser'] : $this->load('getSonata_Templating_NameParserService.php')) && false ?: '_'}, ${($_ = isset($this->services['sonata.templating.locator']) ? $this->services['sonata.templating.locator'] : $this->load('getSonata_Templating_LocatorService.php')) && false ?: '_'});
