<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sonata\AdminBundle\Action\SearchAction' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Action/SearchAction.php';

return $this->services['Sonata\\AdminBundle\\Action\\SearchAction'] = new \Sonata\AdminBundle\Action\SearchAction(${($_ = isset($this->services['sonata.admin.pool']) ? $this->services['sonata.admin.pool'] : $this->getSonata_Admin_PoolService()) && false ?: '_'}, ${($_ = isset($this->services['sonata.admin.search.handler']) ? $this->services['sonata.admin.search.handler'] : $this->load('getSonata_Admin_Search_HandlerService.php')) && false ?: '_'}, ${($_ = isset($this->services['sonata.admin.global_template_registry']) ? $this->services['sonata.admin.global_template_registry'] : $this->getSonata_Admin_GlobalTemplateRegistryService()) && false ?: '_'}, ${($_ = isset($this->services['sonata.admin.breadcrumbs_builder']) ? $this->services['sonata.admin.breadcrumbs_builder'] : $this->load('getSonata_Admin_BreadcrumbsBuilderService.php')) && false ?: '_'}, ${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->getTwigService()) && false ?: '_'});
