<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIewelgx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIewelgx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIewelgx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIewelgx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIewelgx\appDevDebugProjectContainer([
    'container.build_hash' => 'Iewelgx',
    'container.build_id' => '7f5712a6',
    'container.build_time' => 1576816643,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIewelgx');
